DROP TABLE IF EXISTS FLIGHT;

CREATE TABLE FLIGHT (
FL_NUM VARCHAR(10) NOT NULL,
ORIGIN VARCHAR(10) NOT NULL,
DESTINATION VARCHAR(10) NOT NULL,
DEPART_TIME time,
ARRIVAL_TIME time,
PRICE decimal(10,2) NOT NULL
);